name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0

  path_provider: ^2.1.6
  zxcvbn: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_slidable: ^3.1.2
  drift_dev: ^2.34.0
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/LogoEmpresa.png
