// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6RMXRgBw2P-nKYrDQLC3zXran7xV2WPU',
    appId: '1:344442342267:web:43f6c0fa7e7f9e1e24cbde',
    messagingSenderId: '344442342267',
    projectId: 'app-argos-argonautas',
    authDomain: 'app-argos-argonautas.firebaseapp.com',
    storageBucket: 'app-argos-argonautas.firebasestorage.app',
    measurementId: 'G-G589GL1Z18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWkIgxnODegEXYamUOKu45SzJ4xeT-Dz0',
    appId: '1:344442342267:android:cfc3c7c7789244c224cbde',
    messagingSenderId: '344442342267',
    projectId: 'app-argos-argonautas',
    storageBucket: 'app-argos-argonautas.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_eeO64cN35d1pmFfg1LH0M6oAJ2E93rc',
    appId: '1:344442342267:ios:54b885fb2dda1da324cbde',
    messagingSenderId: '344442342267',
    projectId: 'app-argos-argonautas',
    storageBucket: 'app-argos-argonautas.firebasestorage.app',
    iosBundleId: 'br.com.bernadelli.balancas',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_eeO64cN35d1pmFfg1LH0M6oAJ2E93rc',
    appId: '1:344442342267:ios:d08970ad8fdfa2c824cbde',
    messagingSenderId: '344442342267',
    projectId: 'app-argos-argonautas',
    storageBucket: 'app-argos-argonautas.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6RMXRgBw2P-nKYrDQLC3zXran7xV2WPU',
    appId: '1:344442342267:web:e4204a6f47e2621724cbde',
    messagingSenderId: '344442342267',
    projectId: 'app-argos-argonautas',
    authDomain: 'app-argos-argonautas.firebaseapp.com',
    storageBucket: 'app-argos-argonautas.firebasestorage.app',
    measurementId: 'G-T10Q1X3WZ7',
  );
}
